name: Test

on:
  workflow_dispatch:
  push:
    branches:
      - master
      - develop
      - releases/*
    tags:
      - v*
    paths-ignore:
      - '**.md'
  pull_request:
    paths-ignore:
      - '**.md'

env:
  NODE_VERSION: 18.x

jobs:
  test:
    runs-on: ${{ matrix.operating-systems }}
    strategy:
      fail-fast: false
      matrix:
        operating-systems:
          - ubuntu-latest
          - macos-latest
          - windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - uses: actions/cache@v3
        with:
          path: node_modules
          key: ${{ runner.os }}-module-cache-${{ matrix.operating-systems }}-test

      - uses: actions/cache@v3
        with:
          path: .vscode-test
          key: ${{ runner.os }}-code-cache-${{ matrix.operating-systems }}-test

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: npm

      - name: Install node dependencies
        run: yarn

      - name: Run tests
        if: "${{ matrix.operating-systems == 'ubuntu-latest' }}"
        run: xvfb-run yarn test

      - name: Run tests
        if: "${{ matrix.operating-systems != 'ubuntu-latest' }}"
        run: yarn test
